apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vyg6fe3od-go
  janus-idp.io/tekton: vyg6fe3od-go
  backstage.io/kubernetes-id: vyg6fe3od-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vyg6fe3od-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
