apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vyg6fe3od-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vyg6fe3od-go 
  name: vyg6fe3od-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vyg6fe3od-go 
