apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vyg6fe3od-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:4fc45c4534dc8f9268b8a6f194ec559f8ab4b1fe@sha256:c8dab970ecb306cff86b90e3c00aae944fd45bdeaf9bcac2020d436c859a2c62
          name: container-image
